platform: x64

environment:

  matrix:
  - TOXENV: py27
  - TOXENV: py34
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

install:
  - pip install tox

build: off

test_script:
  - tox

