name: Test tunnel for databases connection

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker compose up databases and ssh-server
        run: cd tests && docker-compose up -d
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2 pymysql pymongo
      - name: Run tests
        run: python tests/docker_functional_test.py
