name: Test tunnel for databases connection

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker compose up databases and ssh-server
        run: cd e2e_tests && docker-compose up -d
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install psycopg2 pymysql pymongo
      - name: Run tests
        run: |
          ssh -o  "StrictHostKeyChecking=no"  linuxserver@127.0.0.1 -p 2222 -i ./ssh-server-config/ssh_host_rsa_key -v "uname -a"
          python e2e_tests/run_docker_e2e_tests.py
