name: Test tunnel for databases connection

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker compose up databases and ssh-server
        run: cd e2e_tests && docker-compose up -d
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install psycopg2 pymysql pymongo
      - name: Run tests
        run: python e2e_tests/run_docker_e2e_tests.py
